runtime: python39
entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "false"
  STREAMLIT_SERVER_BASE_URL_PATH: "/" 